import Head from "next/head"
import { DateTime } from "luxon"
export default function Home({ data }) {
    const dt = DateTime.fromISO(data.update).setZone("America/Toronto").toFormat("yyyy-MM-dd")
    return (
        <div>
            <Head>
                <title>Benja Transit3 - Open Data Notice</title>
            </Head>
            <main className="flex min-h-screen flex-col items-center justify-between p-24">
                <h2>City of Ottawa</h2>
                <p>GTFS provided by OC Transpo</p>
                <p>Realtime Data provided by OC Transpo</p>
                <h2>City of Gatineau</h2>
                <p>GTFS & GTFS-RT provided by STO</p>
                <p>This service incorporates the open data provided by the Société de transport de l&apos;Outaouais (STO). STO is not responsible for the accuracy of the information generated by this application. Last update: {dt}</p>
            </main>
        </div>
    )
}

export async function getServerSideProps() {
    // Fetch data from external API

    const res = await fetch("https://benjamin-del.github.io/TransitDB3/update.json")
    const data = await res.json()
    // Pass data to the page via props
    return { props: { data } }
}
